<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p><?= $success ?></p>
    <form method="post">
        <div>
            <label for="name">Nom de la catégorie</label>
            <input type="text" name="name" id="name" value="<?= $categorie->name ?>">
        </div>
        <button class="btn btn-primary">Mettre à jour</button>
    </form>
</body>
</html>